//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductReviews.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OfferStatus = new HashSet<OfferStatu>();
            this.Refunds = new HashSet<Refund>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int ProductID { get; set; }
        public int OrderID { get; set; }
        public string ProductTitle { get; set; }
        public string ProductCategory { get; set; }
        public string ASIN_ISBN { get; set; }
        public string UNSPSC_Code { get; set; }
        public string Seller { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ShipStatus { get; set; }
        public string TrackingInfo { get; set; }
        public Nullable<decimal> ItemSubtotal { get; set; }
        public Nullable<decimal> ItemTax { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public string ProductNotes { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferStatu> OfferStatus { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refund> Refunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
