//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductReviews.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Refund()
        {
            this.OfferStatus = new HashSet<OfferStatu>();
        }
    
        public int RefundID { get; set; }
        public int ProductID { get; set; }
        public string RefundType { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public string PPTransactionID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PPFees { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string GiftCardType { get; set; }
        public string GiftCardNumber { get; set; }
        public string RefundNotes { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferStatu> OfferStatus { get; set; }
        public virtual Product Product { get; set; }
    }
}
