//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductReviews.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> OverallRating { get; set; }
        public Nullable<double> SubRating1 { get; set; }
        public Nullable<double> SubRating2 { get; set; }
        public Nullable<double> SubRating3 { get; set; }
        public string Headline { get; set; }
        public string ReviewDetail { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public string Reviewer { get; set; }
        public string PublicReviewLink { get; set; }
        public string ReviewNotes { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ExternalId { get; set; }
        public string AmazonReviewID { get; set; }
        public string ProductASIN { get; set; }
        public string ProductTitle { get; set; }
        public string ReviewType { get; set; }
        public Nullable<bool> VerifiedPurchase { get; set; }
        public Nullable<bool> Vine { get; set; }
        public Nullable<bool> Zebra { get; set; }
        public string Visibility { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
