//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductReviews.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRefundsNeedMappedToProduct
    {
        public int AgentID { get; set; }
        public string MessengerLink { get; set; }
        public int ProductID { get; set; }
        public Nullable<decimal> ItemSubtotal { get; set; }
        public string ProductTitle { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
